jobs:
 - template: default.yml@templates
 - job: canary
   displayName: "Warning screening"
   pool:
     vmImage: ubuntu-16.04
   steps:
     - template: install-rust.yml@templates
       parameters:
         rust: beta
         components:
           - clippy
     - bash: cargo clippy --all-features -- -D warnings
       displayName: cargo clippy -- -D warnings

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.3
      endpoint: jonhoo
