[package]
name = "bustle"
version = "0.2.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"
license = "Apache-2.0"

readme = "README.md"
description = "Benchmarking harness for concurrent key-value collections"
repository = "https://github.com/jonhoo/bustle.git"

keywords = ["concurrent","benchmark","harness"]
categories = ["concurrency", "development-tools::profiling", "development-tools::testing"]

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "bustle", build = "18" }
maintenance = { status = "experimental" }

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.2"

[[bench]]
name = "arc_mutex_std"
harness = false

[[bench]]
name = "arc_rwlock_std"
harness = false
